#Dockercompose file for deploying geo-api
version: '3'
services:
  geo-api:
    build: .
    container_name: geo-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - GEO_API_MONGODB_URL=mongodb://mymongodb:27017
      - GEO_API_MONGODB_USERNAME=mongo
      - GEO_API_MONGODB_PASSWORD=123456
  mymongodb:
    image: mongo
    container_name: mymongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123456
networks:
  default:
    name: findhotel
