// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"findhotel.com/geo-service/csv"
	"findhotel.com/geo-service/db"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateImporter() csv.Importer {
	clientWrapper := CreateDBClient()
	dispatcher := CreateDispatcher()
	importerImpl := csv.NewImporterImpl(clientWrapper, dispatcher)
	return importerImpl
}

func CreateDispatcher() csv.Dispatcher {
	geoLocationDao := CreateGeoLocationDao()
	dispatcherImpl := csv.NewDispatcherImpl(geoLocationDao)
	return dispatcherImpl
}

func CreateGeoLocationDao() mongodb.GeoLocationDao {
	clientWrapper := CreateDBClient()
	geoLocationDaoImpl := mongodb.NewGeoLocationDaoImpl(clientWrapper)
	return geoLocationDaoImpl
}

func CreateDBClient() mongodb.ClientWrapper {
	clientWrapperImpl := mongodb.NewClientWrapperImpl()
	return clientWrapperImpl
}

// wire.go:

var Set = wire.NewSet(wire.Bind(new(mongodb.ClientWrapper), new(*mongodb.ClientWrapperImpl)))
